version: '3.8'

services:

  app:
    build:
      context: .
      dockerfile: ./microservices/app/Dockerfile
    ports:
      - "4999:5000"
    environment:
      - FLASK_ENV=production
  bisection:
    build:
      context: .
      dockerfile: ./microservices/bisection/Dockerfile
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=production

  newton_raphson:
    build:
      context: .
      dockerfile: ./microservices/newton_raphson/Dockerfile
    ports:
      - "5002:5000"
    environment:
      - FLASK_ENV=production
  secant:
    build:
      context: .
      dockerfile: ./microservices/secant/Dockerfile
    ports:
      - "5003:5000"
    environment:
      - FLASK_ENV=production
  fixed_point:
    build:
      context: .
      dockerfile: ./microservices/fixed_point/Dockerfile
    ports:
      - "5004:5000"
    environment:
      - FLASK_ENV=production
  jacobi:
    build:
      context: .
      dockerfile: ./microservices/jacobi/Dockerfile
    ports:
      - "5005:5000"
    environment:
      - FLASK_ENV=production

  gauss_seidel:
    build:
      context: .
      dockerfile: ./microservices/gauss_seidel/Dockerfile
    ports:
      - "5006:5000"
    environment:
      - FLASK_ENV=production

  broyden:
    build:
      context: .
      dockerfile: ./microservices/broyden/Dockerfile
    ports:
      - "5007:5000"
    environment:
      - FLASK_ENV=production

  simpson:
    build:
      context: .
      dockerfile: ./microservices/simpson/Dockerfile
    ports:
      - "5008:5000"
    environment:
      - FLASK_ENV=production

  trapecio:
    build:
      context: .
      dockerfile: ./microservices/trapecio/Dockerfile
    ports:
      - "5009:5000"
    environment:
      - FLASK_ENV=production

networks:
  default:
    driver: bridge