version: '3.8'

services:
  bisection:
    build:
      context: ./microservices/bisection/
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=production

  newton_raphson:
    build:
      context: ./microservices/newton_raphson
    ports:
      - "5002:5000"
    environment:
      - FLASK_ENV=production
  secant:
    build:
      context: ./microservices/secant
    ports:
      - "5003:5000"
    environment:
      - FLASK_ENV=production
  fixed_point:
    build:
      context: ./microservices/fixed_point
    ports:
      - "5004:5000"
    environment:
      - FLASK_ENV=production
  jacobi:
    build:
      context: ./microservices/jacobi
    ports:
      - "5005:5000"
    environment:
      - FLASK_ENV=production

  gauss_seidel:
    build:
      context: ./microservices/gauss_seidel
    ports:
      - "5006:5000"
    environment:
      - FLASK_ENV=production

# Red opcional para comunicación entre servicios
networks:
  default:
    driver: bridge